const data = [
    {
        id:104030405,
        clase:"motos",
        category:5,
        abreviado:"cfmotomt800touring",
        nombre:"CFMoto MT 800 Touring",
        color:"Azul",
        precio:20190,
        foto: "https://iili.io/HoWB6GI.png",

    },
    {
        id:102010203,
        clase:"motos",
        category:1,
        abreviado:"hondawave110gris",
        nombre:"Honda Wave 110 Gris",
        color:"Gris",
        precio:2490,
        foto: "https://iili.io/Hnlrjx1.png"
    },
    {
        id:102010201,
        clase:"motos",
        category:1,
        abreviado:"hondawave110negra",
        nombre:"Honda Wave 110 Negra",
        color:"Negro",
        precio:2490,
        foto: "https://iili.io/HoWC7wv.png",
    },
    {
        id:102010201,
        clase:"motos",
        category:1,
        abreviado:"hondawave110blanca",
        nombre:"Honda Wave 110 Blanca",
        color:"Blanco",
        precio:2490,
        foto: "https://iili.io/HoWCR9a.png",
    },
    {
        id:106011102,
        clase:"motos",
        category:2,
        abreviado:"hondanavi110blanca",
        nombre:"Honda Navi 110 Blanca",
        color:"Blanco",
        precio:1990,
        foto: "https://iili.io/HoWCfuj.png",
    },
    {
        id:106011105,
        clase:"motos",
        category:2,
        abreviado:"hondanavi110azul",
        nombre:"Honda Navi 110 Azul",
        color:"Azul",
        precio:1990,
        foto: "https://iili.io/HoWCFyb.png",
    },
    {
        id:101010104,
        clase:"motos",
        category:3,
        abreviado:"hondacb1roja",
        nombre:"Honda CB1 125 Roja",
        color:"Rojo",
        precio:2350,
        foto: "https://iili.io/HoWBmZl.png",
    },
    {
        id:105010901,
        clase:"motos",
        category:4,
        abreviado:"hondatwister125negra",
        nombre:"Honda Twister 125 Negra",
        color:"Negro",
        precio:2490,
        cant:1,
        foto: "https://iili.io/HoWCIF1.png"
    },
    {
        id:105010905,
        clase:"motos",
        category:4,
        abreviado:"hondatwister125azul",
        nombre:"Honda Twister 125 Azul",
        color:"Azul",
        precio:2490,
        cant:1,
        foto: "https://iili.io/HoWCoMB.png"
    },
    {
        id:105010904,
        clase:"motos",
        category:4,
        abreviado:"hondatwister125roja",
        nombre:"Honda Twister 125 Roja",
        color:"Rojo",
        precio:2490,
        cant:1,
        foto: "https://iili.io/HoWCTcF.png"
    },
]

module.exports = {
    data
}